#!/bin/bash
# Rebuilds a Moodle Playground bundle with one or more third-party plugins
# baked into its baseline install snapshot, instead of relying on the
# sandbox's runtime installMoodlePlugin blueprint step.
#
# Why this exists: the runtime installMoodlePlugin step runs
# upgrade_noncore() *inside* the booted WASM PHP instance, and a raw fatal
# there escapes moodle-playground's own JS try/catch (Moodle's
# default_exception_handler calls exit(1) first), leaving a plugin's files
# present but its DB registration incomplete - see
# dev-docs/oer-platform/discoveries/2026-07-19-sandbox-thirdparty-plugin-db-install-limitation.md
# for the full trace. The bundle's baseline snapshot, by contrast, is
# generated by moodle-playground's own generate-install-snapshot.sh running
# Moodle's REAL, native admin/cli/install_database.php on ordinary
# (non-WASM) PHP - the same reliable path that installs every core table.
# A plugin present in the Moodle source tree BEFORE that snapshot is
# generated goes through that same reliable path.
#
# This script does NOT modify the playground checkout's own tracked files
# - it only copies plugin source into the checkout's *persistent,
# already-gitignored* source checkout cache (.cache/moodle/<branch>/), which
# survives across ordinary rebuilds (fetch-moodle-source.sh does a `git
# fetch` + `git reset --hard` on that checkout, not a `git clean`, so
# untracked directories like an injected plugin are preserved). oer-sandbox
# still "does not vendor the playground source" in the sense that matters:
# nothing here is committed into the playground checkout, and the plugin
# source itself lives in its own repo, not copied into oer-sandbox.
#
# Usage:
#   BRANCH=MOODLE_502_STABLE ./build-bundle-with-plugins.sh mod:quizquest:/path/to/moodle-mod_quizquest
#
# Each argument is type:name:source-dir. Add more arguments to bake in
# multiple plugins for the same branch/build. The playground checkout is
# PLAYGROUND_DIR (see scripts/common.sh) — run install.sh first if it does
# not exist yet.
set -euo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
source "$SCRIPT_DIR/common.sh"

BRANCH="${BRANCH:-MOODLE_502_STABLE}"

if [ "$#" -eq 0 ]; then
  echo "Usage: BRANCH=<branch> $0 <type:name:source-dir> [more...]" >&2
  exit 1
fi

if [ ! -d "$PLAYGROUND_DIR/.git" ]; then
  echo "ERROR: no playground checkout at $PLAYGROUND_DIR — run install.sh first" >&2
  exit 1
fi

echo "== Fetching/updating Moodle source for $BRANCH ==" >&2
MOODLE_DIR=$("$PLAYGROUND_DIR/scripts/fetch-moodle-source.sh" "$BRANCH")
echo "Source at: $MOODLE_DIR" >&2

# Moodle 5.1+ nests the docroot under public/.
if [ -d "$MOODLE_DIR/public" ]; then
  WEBROOT="$MOODLE_DIR/public"
else
  WEBROOT="$MOODLE_DIR"
fi

for SPEC in "$@"; do
  PLUGIN_TYPE=$(printf '%s' "$SPEC" | cut -d: -f1)
  PLUGIN_NAME=$(printf '%s' "$SPEC" | cut -d: -f2)
  PLUGIN_SRC=$(printf '%s' "$SPEC" | cut -d: -f3-)

  if [ -z "$PLUGIN_TYPE" ] || [ -z "$PLUGIN_NAME" ] || [ -z "$PLUGIN_SRC" ]; then
    echo "ERROR: invalid plugin spec '$SPEC' - expected type:name:source-dir" >&2
    exit 1
  fi
  if [ ! -d "$PLUGIN_SRC" ]; then
    echo "ERROR: plugin source dir does not exist: $PLUGIN_SRC" >&2
    exit 1
  fi

  # Moodle's full plugin-type-to-directory map, shared with bake.sh
  # (scripts/common.sh) — see the note there on why the short mod/block/local
  # list stopped being safe once dependencies became automatic.
  TYPE_DIR="$(oer_plugin_type_dir "$PLUGIN_TYPE")" || exit 1

  TARGET_DIR="$WEBROOT/$TYPE_DIR/$PLUGIN_NAME"
  echo "== Injecting $PLUGIN_TYPE $PLUGIN_NAME: $PLUGIN_SRC -> $TARGET_DIR ==" >&2
  rm -rf "$TARGET_DIR"
  mkdir -p "$TARGET_DIR"
  rsync -a --exclude=.git "$PLUGIN_SRC/" "$TARGET_DIR/"
done

echo "== Clearing the snapshot cache for $BRANCH ==" >&2
# The build's own snapshot-fingerprint (Moodle source commit + build-script
# hash + patches-dir hash) does NOT account for an injected plugin, so a
# stale cached snapshot from a prior (plugin-less) build would otherwise be
# reused silently and this whole exercise would be a no-op. Force a real
# rebuild.
rm -rf "$PLAYGROUND_DIR/.cache/snapshots/$BRANCH"

echo "== Running build-moodle-bundle.sh for $BRANCH (plugins baked in) ==" >&2
(cd "$PLAYGROUND_DIR" && BRANCH="$BRANCH" PHP_BIN="$PHP_BIN" "$PLAYGROUND_DIR/scripts/build-moodle-bundle.sh")

echo "== Done. Bundle for $BRANCH now includes: $* ==" >&2
