# Shared configuration for the oer-sandbox scripts. Sourced, not executed.
#
# Every value can be overridden from the environment so the scripts run on
# any machine — nothing here may hardcode a path that exists only on one
# dev box.
#
#   PLAYGROUND_REPO  Git URL of Moodle Playground (upstream by default).
#   PLAYGROUND_REF   Commit/tag to check out. Pinned so a fresh install is
#                    reproducible; see README "Source pin" for what the
#                    default pin is and how it was chosen.
#   PLAYGROUND_DIR   Where the playground clone lives. Defaults to
#                    ./playground inside this repo (gitignored); point it
#                    at an existing clone to reuse one.
#   BUNDLES          Space-separated bundle specs, each BRANCH[:GIT_REF].
#   DEPLOY_TARGET    Directory the built static tree is rsynced to.
#   TRY_LOCATION     URL path nginx serves the sandbox at.
#   WEB_OWNER        user:group the deployed tree is chowned to; set it
#                    empty to skip the chown entirely.
#   PHP_BIN          PHP CLI used for install-snapshot generation (needs
#                    the sqlite3 extension).

OER_SANDBOX_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

PLAYGROUND_REPO="${PLAYGROUND_REPO:-https://github.com/ateeducacion/moodle-playground.git}"
PLAYGROUND_REF="${PLAYGROUND_REF:-2707585fd78849e33f6f663cb81655de88a96513}"
PLAYGROUND_DIR="${PLAYGROUND_DIR:-$OER_SANDBOX_ROOT/playground}"
BUNDLES="${BUNDLES:-MOODLE_502_STABLE:v5.2.0 MOODLE_500_STABLE}"
DEPLOY_TARGET="${DEPLOY_TARGET:-/srv/oer-sandbox/try}"
TRY_LOCATION="${TRY_LOCATION:-/try/}"
WEB_OWNER="${WEB_OWNER-www-data:www-data}"
PHP_BIN="${PHP_BIN:-$(command -v php || true)}"

# Run privileged steps directly when already root (containers, CI).
SUDO="sudo"
if [ "$(id -u)" -eq 0 ]; then
  SUDO=""
fi

# nginx needs the trailing slash on both the location and the alias.
case "$TRY_LOCATION" in
  */) ;;
  *) TRY_LOCATION="$TRY_LOCATION/" ;;
esac

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "ERROR: required command not found: $1" >&2
    exit 1
  }
}

# Keys the generated config file may set. An unknown key is an error, not a
# silent skip: it is how a config file generated by a newer Exchange meets an
# older script, and a silent skip would build the wrong bundle and report
# success. Prefix forms (SITE_SETTING_*, PLUGIN_ZIP_*, ...) are matched
# separately below.
OER_CONFIG_KEYS="OER_CONFIG_STAMP BUNDLES LANGPACKS TRIAL_DEFAULT_LANG"

# A branch-keyed config key embeds local_oerexchange_pluginallowlist's
# moodlebranch column verbatim (e.g. BAKE_PLUGINS_5.2,
# PLUGIN_ZIP_mod_quizquest_5.2 — moodlebranch is stored "5.2"-style, major
# dot minor; verified against a live allowlist row and against
# config::render()'s real output, not the design doc's illustrative
# MOODLE_502_STABLE-style example). A literal "." is not legal in a bash
# identifier, so printf -v/export/${!name} on the raw key fails outright —
# found empirically running bake.sh against a real generated config, not
# assumed. Every caller that turns a config KEY into a shell variable name,
# on either side (storing here, or looking one up in bake.sh), must run it
# through this same substitution so the two sides agree on the name.
oer_varname() {
  printf '%s' "$1" | tr -c 'A-Za-z0-9_' '_'
}

oer_load_config() {
  local file="$1"
  if [ ! -r "$file" ]; then
    echo "ERROR: config file not readable: $file" >&2
    return 1
  fi

  local line key value
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      ''|'#'*) continue ;;
    esac
    if [[ "$line" != *=* ]]; then
      echo "ERROR: not a KEY=value line in $file: $line" >&2
      return 1
    fi
    key="${line%%=*}"
    value="${line#*=}"

    case "$key" in
      SITE_SETTING_*|SITE_FILTER_*|BAKE_PLUGINS_*|PLUGIN_ZIP_*|PLUGIN_SHA256_*)
        ;;
      *)
        if ! printf '%s' " $OER_CONFIG_KEYS " | grep -q " $key "; then
          local suggestion
          suggestion=$(printf '%s\n' $OER_CONFIG_KEYS | grep -i "^${key:0:6}" | head -1)
          echo "ERROR: unknown config key '$key' in $file${suggestion:+ (did you mean $suggestion?)}" >&2
          return 1
        fi
        ;;
    esac

    # printf -v assigns without evaluating the value: nothing from the file is
    # ever executed. This is the whole reason the file is parsed and not sourced.
    local varname
    varname="$(oer_varname "$key")"
    printf -v "$varname" '%s' "$value"
    export "${varname?}"
  done <"$file"
}
