# Shared configuration for the oer-sandbox scripts. Sourced, not executed.
#
# Every value can be overridden from the environment so the scripts run on
# any machine — nothing here may hardcode a path that exists only on one
# dev box.
#
#   PLAYGROUND_REPO  Git URL of Moodle Playground (upstream by default).
#   PLAYGROUND_REF   Commit/tag to check out. Pinned so a fresh install is
#                    reproducible; see README "Source pin" for what the
#                    default pin is and how it was chosen.
#   PLAYGROUND_DIR   Where the playground clone lives. Defaults to
#                    ./playground inside this repo (gitignored); point it
#                    at an existing clone to reuse one.
#   BUNDLES          Space-separated bundle specs, each BRANCH[:GIT_REF].
#   DEPLOY_TARGET    Directory the built static tree is rsynced to.
#   TRY_LOCATION     URL path nginx serves the sandbox at.
#   WEB_OWNER        user:group the deployed tree is chowned to; set it
#                    empty to skip the chown entirely.
#   PHP_BIN          PHP CLI used for install-snapshot generation (needs
#                    the sqlite3 extension).

OER_SANDBOX_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

PLAYGROUND_REPO="${PLAYGROUND_REPO:-https://github.com/ateeducacion/moodle-playground.git}"
PLAYGROUND_REF="${PLAYGROUND_REF:-2707585fd78849e33f6f663cb81655de88a96513}"
PLAYGROUND_DIR="${PLAYGROUND_DIR:-$OER_SANDBOX_ROOT/playground}"
BUNDLES="${BUNDLES:-MOODLE_502_STABLE:v5.2.0 MOODLE_500_STABLE}"
DEPLOY_TARGET="${DEPLOY_TARGET:-/srv/oer-sandbox/try}"
TRY_LOCATION="${TRY_LOCATION:-/try/}"
WEB_OWNER="${WEB_OWNER-www-data:www-data}"
PHP_BIN="${PHP_BIN:-$(command -v php || true)}"

# Run privileged steps directly when already root (containers, CI).
SUDO="sudo"
if [ "$(id -u)" -eq 0 ]; then
  SUDO=""
fi

# nginx needs the trailing slash on both the location and the alias.
case "$TRY_LOCATION" in
  */) ;;
  *) TRY_LOCATION="$TRY_LOCATION/" ;;
esac

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "ERROR: required command not found: $1" >&2
    exit 1
  }
}

# Keys the generated config file may set. An unknown key is an error, not a
# silent skip: it is how a config file generated by a newer Exchange meets an
# older script, and a silent skip would build the wrong bundle and report
# success. Prefix forms (SITE_SETTING_*, PLUGIN_ZIP_*, ...) are matched
# separately below.
OER_CONFIG_KEYS="OER_CONFIG_STAMP BUNDLES LANGPACKS TRIAL_DEFAULT_LANG"

# A branch-keyed config key embeds local_oerexchange_pluginallowlist's
# moodlebranch column verbatim (e.g. BAKE_PLUGINS_5.2,
# PLUGIN_ZIP_mod_quizquest_5.2 — moodlebranch is stored "5.2"-style, major
# dot minor; verified against a live allowlist row and against
# config::render()'s real output, not the design doc's illustrative
# MOODLE_502_STABLE-style example). A literal "." is not legal in a bash
# identifier, so printf -v/export/${!name} on the raw key fails outright —
# found empirically running bake.sh against a real generated config, not
# assumed. Every caller that turns a config KEY into a shell variable name,
# on either side (storing here, or looking one up in bake.sh), must run it
# through this same substitution so the two sides agree on the name.
oer_varname() {
  printf '%s' "$1" | tr -c 'A-Za-z0-9_' '_'
}

oer_load_config() {
  local file="$1"
  if [ ! -r "$file" ]; then
    echo "ERROR: config file not readable: $file" >&2
    return 1
  fi

  local line key value
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      ''|'#'*) continue ;;
    esac
    if [[ "$line" != *=* ]]; then
      echo "ERROR: not a KEY=value line in $file: $line" >&2
      return 1
    fi
    key="${line%%=*}"
    value="${line#*=}"

    case "$key" in
      SITE_SETTING_*|SITE_FILTER_*|BAKE_PLUGINS_*|PLUGIN_ZIP_*|PLUGIN_SHA256_*)
        ;;
      *)
        if ! printf '%s' " $OER_CONFIG_KEYS " | grep -q " $key "; then
          local suggestion
          suggestion=$(printf '%s\n' $OER_CONFIG_KEYS | grep -i "^${key:0:6}" | head -1)
          echo "ERROR: unknown config key '$key' in $file${suggestion:+ (did you mean $suggestion?)}" >&2
          return 1
        fi
        ;;
    esac

    # printf -v assigns without evaluating the value: nothing from the file is
    # ever executed. This is the whole reason the file is parsed and not sourced.
    local varname
    varname="$(oer_varname "$key")"
    printf -v "$varname" '%s' "$value"
    export "${varname?}"
  done <"$file"
}

# Maps a Moodle plugin type to its directory under the webroot, printing the
# directory on stdout and returning non-zero for an unknown type.
#
# This used to be a three-entry case statement (mod/block/local) duplicated in
# bake.sh and build-bundle-with-plugins.sh, on the reasoning that those were
# the only types the platform was "likely to ever need". That stopped being
# safe once the Exchange began adding a plugin's DEPENDENCIES to the allowlist
# automatically: an admin allowlisting one activity can now pull in a qtype, a
# filter or an admin tool without ever naming it, and an unknown type here
# aborts the whole bake.
#
# The list is Moodle's own, generated from core_component::get_plugin_types()
# on Moodle 5.2.1 (2026-08-02) rather than written from memory. Subplugin
# types are included: they are real plugin types a dependency can legitimately
# have.
oer_plugin_type_dir() {
  local type="$1"
  case "$type" in
    aiplacement) echo "ai/placement" ;;
    aiprovider) echo "ai/provider" ;;
    antivirus) echo "lib/antivirus" ;;
    assignfeedback) echo "mod/assign/feedback" ;;
    assignsubmission) echo "mod/assign/submission" ;;
    auth) echo "auth" ;;
    availability) echo "availability/condition" ;;
    bbbext) echo "mod/bigbluebuttonbn/extension" ;;
    block) echo "blocks" ;;
    booktool) echo "mod/book/tool" ;;
    cachelock) echo "cache/locks" ;;
    cachestore) echo "cache/stores" ;;
    calendartype) echo "calendar/type" ;;
    communication) echo "communication/provider" ;;
    contenttype) echo "contentbank/contenttype" ;;
    coursereport) echo "course/report" ;;
    customfield) echo "customfield/field" ;;
    datafield) echo "mod/data/field" ;;
    dataformat) echo "dataformat" ;;
    datapreset) echo "mod/data/preset" ;;
    editor) echo "lib/editor" ;;
    enrol) echo "enrol" ;;
    factor) echo "admin/tool/mfa/factor" ;;
    fileconverter) echo "files/converter" ;;
    filter) echo "filter" ;;
    format) echo "course/format" ;;
    forumreport) echo "mod/forum/report" ;;
    gradeexport) echo "grade/export" ;;
    gradeimport) echo "grade/import" ;;
    gradepenalty) echo "grade/penalty" ;;
    gradereport) echo "grade/report" ;;
    gradingform) echo "grade/grading/form" ;;
    h5plib) echo "h5p/h5plib" ;;
    local) echo "local" ;;
    logstore) echo "admin/tool/log/store" ;;
    ltiservice) echo "mod/lti/service" ;;
    ltisource) echo "mod/lti/source" ;;
    media) echo "media/player" ;;
    message) echo "message/output" ;;
    mlbackend) echo "lib/mlbackend" ;;
    mod) echo "mod" ;;
    paygw) echo "payment/gateway" ;;
    plagiarism) echo "plagiarism" ;;
    portfolio) echo "portfolio" ;;
    profilefield) echo "user/profile/field" ;;
    qbank) echo "question/bank" ;;
    qbehaviour) echo "question/behaviour" ;;
    qformat) echo "question/format" ;;
    qtype) echo "question/type" ;;
    quiz) echo "mod/quiz/report" ;;
    quizaccess) echo "mod/quiz/accessrule" ;;
    report) echo "report" ;;
    repository) echo "repository" ;;
    scormreport) echo "mod/scorm/report" ;;
    search) echo "search/engine" ;;
    smsgateway) echo "sms/gateway" ;;
    theme) echo "theme" ;;
    tiny) echo "lib/editor/tiny/plugins" ;;
    tool) echo "admin/tool" ;;
    webservice) echo "webservice" ;;
    workshopallocation) echo "mod/workshop/allocation" ;;
    workshopeval) echo "mod/workshop/eval" ;;
    workshopform) echo "mod/workshop/form" ;;
    *)
      echo "ERROR: unknown Moodle plugin type '$type' — regenerate oer_plugin_type_dir() in scripts/common.sh from core_component::get_plugin_types()" >&2
      return 1
      ;;
  esac
}

# Emits the curl flag needed to fetch from an Exchange whose TLS certificate
# does not verify — printed on stdout, empty by default.
#
# Opt-in only, via OER_INSECURE_TLS=1, and deliberately NOT the default. This
# mirrors local_oerexchange's own `sandboxbaseurlinsecure` setting, which
# exists for the same situation from the other direction: a development or
# internal Exchange on a private address and/or a self-signed certificate. A
# normal public Exchange must keep verification on, because these downloads are
# plugin code that gets baked into every trial the sandbox serves — the one
# place a substituted file matters most.
#
# Relaxing verification is survivable here only because the download is
# checksum-verified immediately afterwards against the sha256 the config
# carries, so a substituted file still fails the bake. Without that check this
# flag would be indefensible.
oer_curl_tls_flag() {
  if [ "${OER_INSECURE_TLS:-0}" = "1" ]; then
    printf '%s' '-k'
  fi
}
