#!/bin/bash
# Prints the nginx configuration that serves the deployed sandbox at
# TRY_LOCATION (default /try/); with --install, writes it to
# /etc/nginx/snippets/oer-sandbox-try.conf instead.
#
#   scripts/nginx-try-conf.sh            # print to stdout
#   scripts/nginx-try-conf.sh --install  # write the snippet file
#
# Either way the block must then be included INSIDE the server {} block
# that serves the site, and nginx reloaded — this script never edits a
# vhost itself, because it cannot know which one is yours.
set -euo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
source "$SCRIPT_DIR/common.sh"

ALIAS_DIR="$DEPLOY_TARGET"
case "$ALIAS_DIR" in
  */) ;;
  *) ALIAS_DIR="$ALIAS_DIR/" ;;
esac

conf() {
  cat <<EOF
# OER Exchange "Try it" sandbox — Moodle Playground static files.
# Generated by oer-sandbox/scripts/nginx-try-conf.sh.
#
# Include this inside the server {} block that serves the site, e.g.:
#     include snippets/oer-sandbox-try.conf;
# The ^~ modifier is required: without it a regex location (such as the
# Moodle PHP handler or slasharguments rewrites on the same vhost) could
# capture ${TRY_LOCATION}* requests.
location ^~ ${TRY_LOCATION} {
    alias ${ALIAS_DIR};
    try_files \$uri \$uri/ =404;
}
# nginx older than 1.21.0 ships no MIME type for .wasm — if such a version
# serves application/octet-stream for the bundles' .wasm files, add
# "application/wasm wasm;" to the http-level types (mime.types), NOT to a
# types {} block in this location (that would replace the whole map).
EOF
}

if [ "${1:-}" = "--install" ]; then
  SNIPPET="/etc/nginx/snippets/oer-sandbox-try.conf"
  $SUDO mkdir -p "$(dirname "$SNIPPET")"
  conf | $SUDO tee "$SNIPPET" >/dev/null
  echo "Wrote $SNIPPET"
  echo "Now add this line inside the server {} block that serves the site:"
  echo "    include snippets/oer-sandbox-try.conf;"
  echo "then run: nginx -t && systemctl reload nginx"
else
  conf
fi
